name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v4
        with:
          version: "4.2.2"
      - run: echo "GitHub Actions 工作流创建成功"
